tipfun/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

from board.views import PinListView

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pins/', PinListView.as_view(), name='pins'),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/models.py
from django.db import models


class Pin(models.Model):

    url = models.URLField(null=True, db_index=True)
    img_url = models.URLField(null=True, db_index=True)
    text = models.CharField(max_length=255, blank=True, null=True)
    published_at = models.DateTimeField(null=True)

    def __unicode__(self):
        return self.url

    class Meta:
        ordering = ['-published_at']

board/forms.py
from django import forms


class SearchForm(forms.Form):
    """
    Pin cards search form
    """

    query = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Search for ...',
                   'form': 'search_form'}),
        required=False)

board/views.py
from endless_pagination.views import AjaxListView

from .models import Pin
from .forms import SearchForm


class PinListView(AjaxListView):
    template_name = 'board/pins.html'
    page_template = 'board/pins_page.html'
    model = Pin

    def get_queryset(self):
        qs = super(PinListView, self).get_queryset()
        query = self.request.GET.get('query')
        if query:
            qs = qs.filter(text__icontains=query)
        return qs

    def get_context_data(self, **kwargs):
        context = super(PinListView, self).get_context_data(**kwargs)
        form = SearchForm(self.request.GET or None)
        context.update({'form': form})
        return context

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Pinterest-like Board{% endblock %}</title>
    {% block head %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% endblock %}
  </head>
  <body>
    {% block nav %}
    <div class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" target="">
            <input name="query" type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </div>
    {% endblock %}
    {% block content %}{% endblock %}
    {% block js %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    {% endblock %}
  </body>
</html>

templates/board/pins.html
{% extends "base.html" %}

{% block head %}
    {{ block.super }}
    <style>
        #items .item {
            -moz-border-bottom-colors: none;
            -moz-border-left-colors: none;
            -moz-border-right-colors: none;
            -moz-border-top-colors: none;
            background: linear-gradient(to bottom, #F6F6F6 0%, #EAEAEA 100%) repeat scroll 0 0 transparent;
            border-radius: 4px 4px 4px 4px;
            box-shadow: 0 1px 1px rgba(0, 0, 0, 0.15), 0 2px 1px rgba(0, 0, 0, 0.1), 0 3px 1px rgba(0, 0, 0, 0.05);
            text-shadow: 0 1px 0 #DDDDDD;
            width: 270px;
            margin: 10px;
            float: left;
        }
    </style>
{% endblock %}
{% block content %}
    <div id="items" class="js-masonry"
         data-masonry-options='{ "columnWidth": 290, "itemSelector": ".item" }'>
        {% include "board/pins_page.html" %}
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
    <script src="{{ STATIC_URL }}js/masonry.pkgd.min.js"></script>
    <script src="{{ STATIC_URL }}js/imagesloaded.pkgd.min.js"></script>
    <script>

        var $container = $('#items');

        $container.imagesLoaded(function(){
        $container.masonry({
            itemSelector : '.item',
              columnWidth : 290,
              //isAnimated: true
          });
        });

        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollChunkSize: 10,
            onCompleted: function() {
                $container.imagesLoaded(function(){
                    var masonry = $container.data('masonry');
                    if (masonry !== undefined) {
                        masonry.reloadItems();
                        masonry.layout();
                    }
                });
            }
        });
    </script>
{% endblock %}

templates/board/pins_page.html
{% load endless %}
{% paginate pin_list %}
{% for pin in pin_list %}
    <div class="item">
        <div class="picture">
          <a class="image" href="{{ pin.url }}">
          <img width=250 alt="" src="{{ pin.img_url }}">
        </a>
        <div class="item-content">
          <div class="description">
            {{ pin.text|striptags }}
          </div>
          <div class="meta">
            <span>
              <i class="icon-calendar"></i>
              {{ pin.published_at }}
            </span>
          </div>
        </div>
      </div>
    </div>
{% endfor %}
{% show_more %}